# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'theme_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(556, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.browse_box = QtWidgets.QGroupBox(self.centralwidget)
        self.browse_box.setGeometry(QtCore.QRect(10, 10, 531, 81))
        self.browse_box.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.browse_box.setObjectName("browse_box")

        self.browse_directory = QtWidgets.QPushButton(self.browse_box)
        self.browse_directory.setGeometry(QtCore.QRect(410, 30, 111, 41))
        self.browse_directory.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.browse_directory.setObjectName("browse_directory")

        self.display_directory = QtWidgets.QTextEdit(self.browse_box)
        self.display_directory.setGeometry(QtCore.QRect(10, 30, 391, 41))
        self.display_directory.setObjectName("display_directory")

        self.schedule_box = QtWidgets.QGroupBox(self.centralwidget)
        self.schedule_box.setGeometry(QtCore.QRect(10, 100, 531, 121))
        self.schedule_box.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.schedule_box.setObjectName("schedule_box")

        self.start_display = QtWidgets.QLCDNumber(self.schedule_box)
        self.start_display.setGeometry(QtCore.QRect(90, 40, 61, 23))
        self.start_display.setObjectName("start_display")

        self.stop_display = QtWidgets.QLCDNumber(self.schedule_box)
        self.stop_display.setGeometry(QtCore.QRect(90, 80, 61, 23))
        self.stop_display.setObjectName("stop_display")

        self.start_label = QtWidgets.QLabel(self.schedule_box)
        self.start_label.setGeometry(QtCore.QRect(20, 40, 60, 16))
        self.start_label.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.start_label.setObjectName("start_label")

        self.stop_label = QtWidgets.QLabel(self.schedule_box)
        self.stop_label.setGeometry(QtCore.QRect(20, 80, 60, 16))
        self.stop_label.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.stop_label.setObjectName("stop_label")

        self.start_slider = QtWidgets.QSlider(self.schedule_box)
        self.start_slider.setGeometry(QtCore.QRect(170, 40, 251, 22))
        self.start_slider.setOrientation(QtCore.Qt.Horizontal)
        self.start_slider.setObjectName("start_slider")

        self.stop_slider = QtWidgets.QSlider(self.schedule_box)
        self.stop_slider.setGeometry(QtCore.QRect(170, 80, 251, 22))
        self.stop_slider.setOrientation(QtCore.Qt.Horizontal)
        self.stop_slider.setObjectName("stop_slider")

        self.now_setting = QtWidgets.QPushButton(self.schedule_box)
        self.now_setting.setGeometry(QtCore.QRect(440, 30, 81, 41))
        self.now_setting.setObjectName("now_setting")

        self.in_16h_setting = QtWidgets.QPushButton(self.schedule_box)
        self.in_16h_setting.setGeometry(QtCore.QRect(440, 70, 81, 41))
        self.in_16h_setting.setObjectName("in_16h_setting")

        self.shift_box = QtWidgets.QGroupBox(self.centralwidget)
        self.shift_box.setGeometry(QtCore.QRect(10, 230, 531, 121))
        self.shift_box.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.shift_box.setObjectName("shift_box")

        self.shift_label = QtWidgets.QLabel(self.shift_box)
        self.shift_label.setGeometry(QtCore.QRect(40, 20, 491, 51))
        self.shift_label.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.shift_label.setObjectName("shift_label")

        self.shift_choice = QtWidgets.QSpinBox(self.shift_box)
        self.shift_choice.setGeometry(QtCore.QRect(40, 60, 111, 41))
        self.shift_choice.setObjectName("shift_choice")

        self.label = QtWidgets.QLabel(self.shift_box)
        self.label.setGeometry(QtCore.QRect(170, 70, 341, 16))
        self.label.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.label.setObjectName("label")

        self.errors_display = QtWidgets.QTextBrowser(self.centralwidget)
        self.errors_display.setGeometry(QtCore.QRect(10, 370, 321, 41))
        self.errors_display.setObjectName("errors_display")

        self.start_program = QtWidgets.QPushButton(self.centralwidget)
        self.start_program.setGeometry(QtCore.QRect(340, 370, 201, 41))
        self.start_program.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.start_program.setObjectName("start_program")

        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(340, 420, 201, 41))
        self.clear.setStyleSheet("font: 13pt \"Lucida Grande\";")
        self.clear.setObjectName("clear")

        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 420, 321, 38))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 24))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Dynamic wallpaper & theme"))

        self.browse_box.setTitle(_translate("MainWindow", "Browse directory"))
        self.browse_directory.setText(_translate("MainWindow", "Browse"))

        self.schedule_box.setTitle(_translate("MainWindow", "Schedule Task"))

        self.start_label.setText(_translate("MainWindow", "Start at :"))
        self.stop_label.setText(_translate("MainWindow", "Stop at :"))

        self.now_setting.setText(_translate("MainWindow", "now"))
        self.in_16h_setting.setText(_translate("MainWindow", "+ 16h"))

        self.shift_box.setTitle(_translate("MainWindow", "Shift"))

        self.shift_label.setText(_translate("MainWindow", "You must choose "
                                            "the frame at which the program "
                                            "will start iterate"))

        self.label.setText(_translate("MainWindow", "(Default 0 means no "
                                      "shift, will start with the first one)"))

        self.start_program.setText(_translate("MainWindow", "Start program"))
        self.clear.setText(_translate("MainWindow", "Clear inputs"))
